name: Build Exegol Light from Git

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build Exegol Light Image
      run: |
        docker build \
          https://github.com/ThePorgs/Exegol-images.git#c2f942bb8e72fc74a411339c66691eeaf883ff88 \
          -f light.dockerfile \
          -t exegol/light:ci
