name: Build Exegol Light Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build light image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: light.dockerfile
        push: false
        tags: exegol/light:custom
